name: sumo_av_gym
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10.11
  - pip
  - pip:
    - torch
    - torchvision
    - torchaudio
    - numpy==1.23.5
    - matplotlib
    - gym
    - scipy
